language: java
jdk:
- openjdk10
install: "/bin/true"
script: mvn clean install -q -B
cache:
  directories:
  - "$HOME/.cache"
env:
  global:
  - secure: FmDxgl6KO11ZjbJtqhFvGYE6UKTuV3nHCG/G4zWY9ikGb2FHAW3gjPrCS5pA0H12DRleXQJDF6GrAXnI3Y1ig3MIMzLX/QRB06LKyrLMBp3pJGjz/0YvP66q4hdz39/eWic4Bqo78Ukgm78md+lffq3lAl/RJf7sxBTpyZX6LTqAs+qbFoSnYiE1GKgScy41ZLCQdUm0+oeMvo4UzAFk75bQBTD2ytmmpE8JVEHsN+xQ+4ONm9O2FbNHk3lM66JTIhaq9oFDIZroJCnB+v2iBbNAnhP3RzawglrGcB4+ag2m/4xsJBG+Tz6My0l6k9h2+SNfHrKT9bKYk8nYnNX8er+LVG/tSsRgUzc/KziUhl9Q3JJrvoOlufdkX0+y2ZcBqZh7EcHQ6ztkhCaWpe6ap/1e7OC4xiU7kRe6acPovMqoBwFoTETH4jrStasJHEGhJ20Ex9xGe1MTX3Fuun0fdOmNjw3A4wejMwU4bScwn5/jIiiBFckrk/7Eg93NlcAPKJboKkHoD5oEgBrFXKetu+IgBygSVh0u5spFovcDHG3lVzd5Pvnkf10G4o/L1ayIHZkdt5C2TrkBAFgVZSm4g3v9GNMZmhJ7isKhap0qzQiFnSNIFBVcv2HngfVWW3ha3ft3Tp7iXBDNf4JcY/qV8G1XtsqbfRloZsQu8T8Gso8=
  - secure: X99Wdpd6HtmvLPSbYomh4HViQ8N92g8eURIkfGZ8tkFbRartyNcZyg5C9ZrjnGnYAyY405i3i2Q8JpbqgNjPI1n9O/99+0xPFR+JypzSDMWx7MCWzoBmptkULHNwJmo9rk1X0dJd+tVtGhoMLfsAcYMqyIsrJ/0HOmX+vHTLySyA4A+aIWbPDGMUvFJG28RajCC6qAxaObtRbZmYq1Hzqw2zbajOZVF86T/QQO43gs5xwVIpP1ZZ57ScNJI/A+7BsLtzj85ayPP7GWjc/64Lhoge+iQzeu2l4+30VmKu3O5kjxePikJTtuOm1ekoiXqBE0uoKCZi58/B3e+SHiqkzo7F5gUAFp2N3G1in8QXUUPd+iBVlDil42pZ8sFCXcbu4lVoifCZ8C4DUR8ZGzVTMqnpK1KJGZFac0hFBcABD0nNsUKUjbl2WKD3Tu15/eao4CXz9jl4g1fTEXE7/LG7oPBZTZEqXjUMdVpoPl6gQhdvP9BVSbLfh6ooIXfsrNCrbRAwLpv5G+PMv2z/ExirFfMTTAFsP4PM0RffBW8daWeRCipXY5khY7+o4c2g7dKogmSUnqNiLEE2bHE5mSfrixpJQkE2If7k88OhMPTPiC3RpTo69FpMpHtdZLlzwvKHfTWcESe+jwo9/kc5PYQhQF2oNMUAAUc9EJklrERzQFY=
  - secure: rmwhB6pVIFLX+nX9PdwvwXqbTcGLaDUndiNXwBH+YA7GAMptMu/ihe+skqJwKIstjn6mLL7rkh5nk+yd25IbMLWMrnRZCWvpFgu+95D63g4xK4uQChumi1SZGlhnD6xYvXLJW5gDpl/QJ9R2NpbIZcsrXvvga3mnOgwB/g5QqYPQJeROeiIA6/r9nuGuQaQ77ZIyKiO4SkdrVOS+P5GzGl6oakliQfWi1sUBiKuwe7u7GjBM0oapffjxxzURSgBmdqCnwgpu6heT5eRTFnmgzOptQKwknDNdaUWjaVFFiqxt8IeQi3ltVY1/SVBruNrg95rQZ5OFi0Pf/I5sh2WMEyiJ4w50fLFNbhxWGczv2Z9ijb4/aMEV2J4ggXBIThLFqpUHt3OM2wju1WQWybwEq4UoTTVNvsWBcnpUMvtoAyzFoFzmgoRcXixUgQ7EwnDZ26MkEpgRwKNlJRZW4jKX68N0knQHHjQrFUm86jrqBq7OW52xGgcODqvFUtIenD9zMwRjBA0HZPUgzSHNfUIkBIrmHo9yE6aN26+QTDll4De8jHLtAq+Q9WUzyeZaaaJ9tZs5Rn7Mx1tJ3sLpxXQ5qAXsrnVweRhrBkBj76Cc+2KAzJ2Uo0WFTViE1DV3jNu2waT4B01Ft3bUwaYItsEVWg08SO9gB0pnvrWNHGnzLIA=
  - secure: KXiAyGLrOyhDkT1R5aurTrTwSJzujnwi4TtvAnlFHSqae1YpYvVsAeJWlr2qxAm+8JX2Kth+/r0mb4tkSQZnF92VzJ3H+FEWgXnOUqi2zsvHFT0vxV+L5agE2b3bPjXuxIPKZlVJ3UdwKiAyYgzgyFFP1NzEWUnLNZTSDhRzkFz4W5pJ2Sz6o+1kNJCJ/w9EV8IUnkb4lw98zsIx32/fAj/JrEFiot0/eyOEqCMecqJ5XGHM0cPxjdTLFsh99UhycVXBNgAUBeb3bRK0zP8Ks0xOI3ntVeW1T+0N05cu4SMqtijaQzZic/n8a4OAomkaAVvMdu8Nh0pdLEDmlxCWSnKPz7eR5d2d7aqV+2VTnzVmRJEv61a1sNx5IEZydIwrBuLfjnOjCQShotRK5WvC1yTcr7VuG9sXgwKevMDpQvVpRygIEfSoZfcZDi4sCwc6CeCq1QnPm1fy5cL5jGDro5qKCFzJb50pJRAkIfW8dAEPtDVx4DcgS36f3aJDGXh1A68BtmJNATid6IYtjiucsA1/L0nwLSz637BFKlUyxf0oqIHOTZy0KJeHXUiza2YF/4G8GemDuf/2d0v9mc7mp4YT7f/Bf3qmOyBAjVFMYZtl4GTOdAoXRqVlQMSAzO+3WDQCFt37BxpymDTm4D8p6YpFAB7JZsF5wONCgjogHKw=
before_deploy:
- openssl aes-256-cbc -K $encrypted_044baa266d1a_key -iv $encrypted_044baa266d1a_iv
  -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
deploy:
- skip_cleanup: true
  provider: script
  script: "./deploy"
  on:
    branch: master
- skip_cleanup: true
  provider: script
  script: "./deploy"
  on:
    tags: true
