//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.13 at 11:34:19 PM MST 
//


package org.dataone.service.types.v2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.dataone.ns.service.types.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LogEntry_QNAME = new QName("http://ns.dataone.org/service/types/v2.0", "logEntry");
    private final static QName _MediaType_QNAME = new QName("http://ns.dataone.org/service/types/v2.0", "mediaType");
    private final static QName _ObjectFormat_QNAME = new QName("http://ns.dataone.org/service/types/v2.0", "objectFormat");
    private final static QName _SystemMetadata_QNAME = new QName("http://ns.dataone.org/service/types/v2.0", "systemMetadata");
    private final static QName _OptionList_QNAME = new QName("http://ns.dataone.org/service/types/v2.0", "optionList");
    private final static QName _NodeList_QNAME = new QName("http://ns.dataone.org/service/types/v2.0", "nodeList");
    private final static QName _Log_QNAME = new QName("http://ns.dataone.org/service/types/v2.0", "log");
    private final static QName _Property_QNAME = new QName("http://ns.dataone.org/service/types/v2.0", "property");
    private final static QName _ObjectFormatList_QNAME = new QName("http://ns.dataone.org/service/types/v2.0", "objectFormatList");
    private final static QName _Node_QNAME = new QName("http://ns.dataone.org/service/types/v2.0", "node");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.dataone.ns.service.types.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LogEntry }
     * 
     */
    public LogEntry createLogEntry() {
        return new LogEntry();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link ObjectFormatList }
     * 
     */
    public ObjectFormatList createObjectFormatList() {
        return new ObjectFormatList();
    }

    /**
     * Create an instance of {@link SystemMetadata }
     * 
     */
    public SystemMetadata createSystemMetadata() {
        return new SystemMetadata();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link NodeList }
     * 
     */
    public NodeList createNodeList() {
        return new NodeList();
    }

    /**
     * Create an instance of {@link Log }
     * 
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link ObjectFormat }
     * 
     */
    public ObjectFormat createObjectFormat() {
        return new ObjectFormat();
    }

    /**
     * Create an instance of {@link OptionList }
     * 
     */
    public OptionList createOptionList() {
        return new OptionList();
    }

    /**
     * Create an instance of {@link MediaType }
     * 
     */
    public MediaType createMediaType() {
        return new MediaType();
    }

    /**
     * Create an instance of {@link MediaTypeProperty }
     * 
     */
    public MediaTypeProperty createMediaTypeProperty() {
        return new MediaTypeProperty();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogEntry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v2.0", name = "logEntry")
    public JAXBElement<LogEntry> createLogEntry(LogEntry value) {
        return new JAXBElement<LogEntry>(_LogEntry_QNAME, LogEntry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v2.0", name = "mediaType")
    public JAXBElement<MediaType> createMediaType(MediaType value) {
        return new JAXBElement<MediaType>(_MediaType_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectFormat }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v2.0", name = "objectFormat")
    public JAXBElement<ObjectFormat> createObjectFormat(ObjectFormat value) {
        return new JAXBElement<ObjectFormat>(_ObjectFormat_QNAME, ObjectFormat.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemMetadata }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v2.0", name = "systemMetadata")
    public JAXBElement<SystemMetadata> createSystemMetadata(SystemMetadata value) {
        return new JAXBElement<SystemMetadata>(_SystemMetadata_QNAME, SystemMetadata.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v2.0", name = "optionList")
    public JAXBElement<OptionList> createOptionList(OptionList value) {
        return new JAXBElement<OptionList>(_OptionList_QNAME, OptionList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v2.0", name = "nodeList")
    public JAXBElement<NodeList> createNodeList(NodeList value) {
        return new JAXBElement<NodeList>(_NodeList_QNAME, NodeList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Log }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v2.0", name = "log")
    public JAXBElement<Log> createLog(Log value) {
        return new JAXBElement<Log>(_Log_QNAME, Log.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Property }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v2.0", name = "property")
    public JAXBElement<Property> createProperty(Property value) {
        return new JAXBElement<Property>(_Property_QNAME, Property.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectFormatList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v2.0", name = "objectFormatList")
    public JAXBElement<ObjectFormatList> createObjectFormatList(ObjectFormatList value) {
        return new JAXBElement<ObjectFormatList>(_ObjectFormatList_QNAME, ObjectFormatList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Node }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v2.0", name = "node")
    public JAXBElement<Node> createNode(Node value) {
        return new JAXBElement<Node>(_Node_QNAME, Node.class, null, value);
    }

}
