//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.13 at 11:34:19 PM MST 
//


package org.dataone.service.types.v1_1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.dataone.ns.service.types.v1_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _QueryEngineDescription_QNAME = new QName("http://ns.dataone.org/service/types/v1.1", "queryEngineDescription");
    private final static QName _QueryEngineList_QNAME = new QName("http://ns.dataone.org/service/types/v1.1", "queryEngineList");
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.dataone.ns.service.types.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryEngineDescription }
     * 
     */
    public QueryEngineDescription createQueryEngineDescription() {
        return new QueryEngineDescription();
    }

    /**
     * Create an instance of {@link QueryEngineList }
     * 
     */
    public QueryEngineList createQueryEngineList() {
        return new QueryEngineList();
    }

    /**
     * Create an instance of {@link QueryField }
     * 
     */
    public QueryField createQueryField() {
        return new QueryField();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryEngineDescription }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1.1", name = "queryEngineDescription")
    public JAXBElement<QueryEngineDescription> createQueryEngineDescription(QueryEngineDescription value) {
        return new JAXBElement<QueryEngineDescription>(_QueryEngineDescription_QNAME, QueryEngineDescription.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryEngineList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1.1", name = "queryEngineList")
    public JAXBElement<QueryEngineList> createQueryEngineList(QueryEngineList value) {
        return new JAXBElement<QueryEngineList>(_QueryEngineList_QNAME, QueryEngineList.class, null, value);
    }

}
